export enum CRAWLER_TYPE {
  LD_JSON = "LD_JSON",
  META = "META",
  PERFORMANCE = "PERFORMANCE",
  ANCHOR = "ANCHOR",
}

export enum CHROME_MESSAGE {
  LD_JSON = "LD_JSON_M",
  META = "META_M",
  PERFORMANCE = "PERFORMANCE_M",
  ANCHOR = "ANCHOR_M",
}
